import { cleanSlug, json, parseJson, requiredHeader } from "./shared";
import { cloudflare, deployBoundWorker, responseJson } from "./providers";
export async function handleCloudflare(request: Request, path: string): Promise<Response | null> {
  const account = () => requiredHeader(request, "x-cloudflare-account-id");
  if (request.method === "GET" && path === "/api/cloudflare/workers") { const r = await cloudflare(request, `/accounts/${encodeURIComponent(account())}/workers/scripts`); return json(await responseJson(r), r.status); }
  if (request.method === "POST" && path === "/api/cloudflare/d1") { const b = await parseJson(request); const r = await cloudflare(request, `/accounts/${encodeURIComponent(account())}/d1/database`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name: cleanSlug(b.name) }) }); return json(await responseJson(r), r.status); }
  if (request.method === "POST" && path === "/api/cloudflare/r2") { const b = await parseJson(request); const r = await cloudflare(request, `/accounts/${encodeURIComponent(account())}/r2/buckets`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name: cleanSlug(b.name) }) }); return json(await responseJson(r), r.status); }
  if (request.method === "POST" && path === "/api/cloudflare/d1/query") { const b = await parseJson(request); const id = String(b.databaseId ?? "").trim(); const sql = String(b.sql ?? "").trim(); if (!/^[0-9a-f-]{32,36}$/i.test(id) || !sql || sql.length > 500000) throw new Error("Invalid D1 database ID or SQL"); const r = await cloudflare(request, `/accounts/${encodeURIComponent(account())}/d1/database/${encodeURIComponent(id)}/query`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ sql }) }); return json(await responseJson(r), r.status); }
  if (request.method === "PUT" && path === "/api/cloudflare/worker") { const b = await parseJson(request); const code = String(b.code ?? ""); if (!code || code.length > 1000000) throw new Error("Worker code is empty or too large"); return json(await deployBoundWorker(request, account(), cleanSlug(b.name), code, String(b.d1Id ?? "").trim() || undefined, String(b.r2Bucket ?? "").trim() || undefined)); }
  if (request.method === "DELETE" && path.startsWith("/api/cloudflare/worker/")) { const name = cleanSlug(decodeURIComponent(path.split("/").pop() ?? "")); const r = await cloudflare(request, `/accounts/${encodeURIComponent(account())}/workers/scripts/${encodeURIComponent(name)}`, { method: "DELETE" }); return json(await responseJson(r), r.status); }
  return null;
}
