import { AUTH_MIGRATION } from "./migration";
import { authPackage, authWorker, authWrangler } from "./templates";
import { cloudflare, deployBoundWorker, github, githubCreateOrUpdateFile, providerResult } from "./providers";
import { cleanSlug, cleanTitle, errorMessage, json, parseJson, requiredHeader } from "./shared";
import { connectBuilds } from "./builds";

export async function createAuthApp(request: Request): Promise<Response> {
  const body = await parseJson(request); const accountId = requiredHeader(request, "x-cloudflare-account-id");
  const slug = cleanSlug(body.slug); const title = cleanTitle(body.title); const completed: string[] = []; const warnings: string[] = [];
  try {
    const repo = await providerResult<{ id: number; name: string; html_url: string; owner: { id: number; login: string } }>(await github(request, "/user/repos", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name: slug, description: `${title} — Cloudflare full-stack authentication app`, private: Boolean(body.private), auto_init: true }) }), "Create GitHub repository");
    completed.push("GitHub repository created");
    const databaseName = `${slug}-db`;
    const database = await providerResult<{ uuid: string }>(await cloudflare(request, `/accounts/${encodeURIComponent(accountId)}/d1/database`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name: databaseName }) }), "Create D1 database");
    completed.push("D1 database created");
    const bucketName = `${slug}-files`;
    await providerResult(await cloudflare(request, `/accounts/${encodeURIComponent(accountId)}/r2/buckets`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name: bucketName }) }), "Create R2 bucket");
    completed.push("R2 bucket created");
    await providerResult(await cloudflare(request, `/accounts/${encodeURIComponent(accountId)}/d1/database/${encodeURIComponent(database.uuid)}/query`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ sql: AUTH_MIGRATION }) }), "Apply D1 migration");
    completed.push("Database migration applied");
    const code = authWorker(title);
    const readme = `# ${title}\n\nGenerated by Dev Control Center. Includes real sign-up/sign-in, HttpOnly sessions, D1, and private R2 uploads.\n`;
    const files: Array<[string, string]> = [["package.json", authPackage(slug)], ["wrangler.jsonc", authWrangler(slug, database.uuid, databaseName, bucketName)], ["src/index.js", code], ["migrations/0001.sql", AUTH_MIGRATION], ["README.md", readme], [".gitignore", "node_modules/\n.wrangler/\n.dev.vars\n"]];
    for (const [path, content] of files) await githubCreateOrUpdateFile(request, repo.owner.login, repo.name, path, content, `Add ${path}`);
    completed.push("Application files pushed to GitHub");
    await deployBoundWorker(request, accountId, slug, code, database.uuid, bucketName); completed.push("Worker deployed with D1 and R2 bindings");
    await providerResult(await cloudflare(request, `/accounts/${encodeURIComponent(accountId)}/workers/scripts/${encodeURIComponent(slug)}/subdomain`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ enabled: true, previews_enabled: true }) }), "Enable workers.dev URL");
    completed.push("Public workers.dev URL enabled");
    if (Boolean(body.connectBuilds)) try { await connectBuilds(request, accountId, slug, repo); completed.push("GitHub automatic builds connected"); } catch (error) { warnings.push(errorMessage(error)); }
    let publicUrl: string | null = null;
    try { const sub = await providerResult<{ subdomain: string }>(await cloudflare(request, `/accounts/${encodeURIComponent(accountId)}/workers/subdomain`), "Read account subdomain"); if (sub.subdomain) publicUrl = `https://${slug}.${sub.subdomain}.workers.dev`; } catch (error) { warnings.push(errorMessage(error)); }
    return json({ ok: true, repository: repo.html_url, worker: slug, public_url: publicUrl, d1: { name: databaseName, id: database.uuid }, r2: { name: bucketName }, completed, warnings }, 201);
  } catch (error) { return json({ error: errorMessage(error), completed, warnings }, 502); }
}
